In [128]:
import pandas as pd
import numpy as np

In [129]:
# 1
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))

ser1 = pd.Series(mylist)
ser2 = pd.Series(myarr)
ser3 = pd.Series(mydict)
print(ser3)

a     0
b     1
c     2
e     3
d     4
     ..
v    21
w    22
x    23
y    24
z    25
Length: 26, dtype: int32


In [130]:
# 2 
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser = pd.Series(mydict)
df = ser.to_frame().reset_index()
print(df.head())

  index  0
0     a  0
1     b  1
2     c  2
3     e  3
4     d  4


In [131]:
# 3
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser1 = pd.Series(mylist)
ser2 = pd.Series(myarr)

df = pd.concat([ser1, ser2], axis=1)
df = pd.DataFrame({ "ser1": ser1, "ser2": ser2 })
print(df)

   ser1  ser2
0     a     0
1     b     1
2     c     2
3     e     3
4     d     4
..  ...   ...
21    v    21
22    w    22
23    x    23
24    y    24
25    z    25

[26 rows x 2 columns]


In [132]:
# 4
mylist = list('abcedfghijklmnopqrstuvwxyz')
ser = pd.Series(mylist)
ser.name = "latin_letters"
print(ser)

0     a
1     b
2     c
3     e
4     d
     ..
21    v
22    w
23    x
24    y
25    z
Name: latin_letters, Length: 26, dtype: object


In [133]:
# 5
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])
res = ser1[~ser1.isin(ser2)]
print(res)

0    1
1    2
2    3
dtype: int64


In [134]:
# 6
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

union = pd.Series(np.union1d(ser1, ser2))
intersect = pd.Series(np.intersect1d(ser1, ser2))
res = union[~union.isin(intersect)]
print(res)

0    1
1    2
2    3
5    6
6    7
7    8
dtype: int64


In [135]:
# 7
ser = pd.Series(np.random.normal(10, 5, 25))
results = np.percentile(ser, q=[0, 25, 50, 75, 100])
print(results)

[ 0.94939475  7.38299431  9.17600237 12.42646601 18.45765908]


In [136]:
# 8
ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))
print(ser.value_counts())

e    6
g    6
a    4
b    4
f    4
h    2
d    2
c    2
Name: count, dtype: int64


In [137]:
# 9
np.random.RandomState(100)
ser = pd.Series(np.random.randint(1, 5, [12]))

print("Топ 2:", ser.value_counts())
ser[~ser.isin(ser.value_counts().index[:2])] = "Прочее"
print("\n")
print(ser)

Топ 2: 1    4
2    3
3    3
4    2
Name: count, dtype: int64


0          1
1          1
2          2
3          1
4     Прочее
       ...  
7     Прочее
8          1
9          2
10         2
11    Прочее
Length: 12, dtype: object


C:\Users\ngk\AppData\Local\Temp\ipykernel_9852\3163159261.py:6: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'Прочее' has dtype incompatible with int32, please explicitly cast to a compatible dtype first.
  ser[~ser.isin(ser.value_counts().index[:2])] = "Прочее"


In [138]:
# 10
ser = pd.Series(np.random.random(20))
cut_ser = pd.qcut(
                ser, 
                q=[0, .1, .2, .3, .4, .5, .6, .7, .8, .9, 1], 
                labels=['1st', '2nd', '3rd', '4th', '5th', '6th', '7th', '8th', '9th', '10th']
)
print(cut_ser)

0      5th
1      3rd
2     10th
3      1st
4      1st
      ... 
15     2nd
16     7th
17     9th
18     8th
19     5th
Length: 20, dtype: category
Categories (10, object): ['1st' < '2nd' < '3rd' < '4th' ... '7th' < '8th' < '9th' < '10th']


In [139]:
# 11
ser = pd.Series(np.random.randint(1, 10, 35))
df = pd.DataFrame(ser.values.reshape(7, 5))
df

0  1  2  3  4
0  5  3  2  2  7
1  2  5  1  8  4
2  2  5  2  1  6
3  8  5  6  3  8
4  8  5  7  3  1
5  2  5  8  5  6
6  9  7  4  4  1

In [140]:
# 12
ser = pd.Series(np.random.randint(1, 10, 7))
print(ser)
indexes = np.argwhere(ser % 3 == 0)
print(indexes)

0    6
1    2
2    5
3    3
4    5
5    1
6    4
dtype: int32
[[0]
 [3]]


In [141]:
# 13
ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
poses = ser.take([0, 4, 8, 14, 20])
print(poses)

0     a
4     e
8     i
14    o
20    u
dtype: object


In [142]:
# 14
ser1 = pd.Series(range(5))
ser2 = pd.Series(list('abcde'))
df = pd.concat([ser1, ser2], axis=1)
df

0  1
0  0  a
1  1  b
2  2  c
3  3  d
4  4  e

In [143]:
# 15
ser1 = pd.Series([10, 9, 6, 5, 3, 1, 12, 8, 13])
ser2 = pd.Series([1, 3, 10, 13])

[pd.Index(ser1).get_loc(i) for i in ser2]

[5, 4, 0, 8]

In [144]:
# 16
truth = pd.Series(range(10))
pred = pd.Series(range(10)) + np.random.random(10)
print(truth, "\n", pred)
print("error", np.mean((truth - pred) ** 2))

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64 
 0    0.904670
1    1.969347
2    2.385608
3    3.040271
4    4.395416
5    5.305087
6    6.521861
7    7.010720
8    8.592130
9    9.852753
dtype: float64
error 0.35080677339150246


In [145]:
# 17
ser = pd.Series(['how', 'to', 'kick', 'ass?'])
print(ser.map(lambda word: word.capitalize()))

0     How
1      To
2    Kick
3    Ass?
dtype: object


In [146]:
# 18
ser = pd.Series(['how', 'to', 'kick', 'ass?'])
print(ser.map(lambda word: len(word)))

0    3
1    2
2    4
3    4
dtype: int64


In [147]:
# 19
ser = pd.Series([1, 3, 6, 10, 15, 21, 27, 35])
print(ser.diff().tolist())
print(ser.diff().diff().tolist())

[nan, 2.0, 3.0, 4.0, 5.0, 6.0, 6.0, 8.0]
[nan, nan, 1.0, 1.0, 1.0, 1.0, 0.0, 2.0]


In [148]:
# 20
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])
ser.map(lambda date: pd.to_datetime(date))
ser

0         01 Jan 2010
1          02-02-2011
2            20120303
3          2013/04/04
4          2014-05-05
5    2015-06-06T12:20
dtype: object

In [149]:
# 21
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])
dates = ser.map(lambda date: pd.to_datetime(date))
print("Date:", dates.dt.day.tolist())
print("Week number:", dates.dt.isocalendar().week.tolist())
print("Day number of year:", dates.dt.dayofyear.tolist())
print("Day of week:", dates.dt.day_name().tolist())

Date: [1, 2, 3, 4, 5, 6]
Week number: [53, 5, 9, 14, 19, 23]
Day number of year: [1, 33, 63, 94, 125, 157]
Day of week: ['Friday', 'Wednesday', 'Saturday', 'Thursday', 'Monday', 'Saturday']


In [150]:
# 22
ser = pd.Series(['Jan 2010', 'Feb 2011', 'Mar 2012'])
dates = ser.map(lambda date: pd.to_datetime(date).replace(day = 4))
print(dates)

0   2010-01-04
1   2011-02-04
2   2012-03-04
dtype: datetime64[ns]


In [151]:
# 23
from collections import Counter
ser = pd.Series(['Apple', 'Orange', 'Plan', 'Python', 'Money'])
mask = ser.map(lambda x: sum([Counter(x.lower()).get(i, 0) for i in list('eyuioa')]) >= 2)
res = ser[mask]
print(res)

0     Apple
1    Orange
3    Python
4     Money
dtype: object


In [152]:
# 24
import re
emails = pd.Series(['buying books at amazom.com', 'rameses@egypt.com', 'matt@t.co', 'narendra@modi.com'])
pattern ='[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,4}'

print(emails[emails.map(lambda email: bool(re.match(pattern, email)))])

1    rameses@egypt.com
2            matt@t.co
3    narendra@modi.com
dtype: object


In [153]:
# 25
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))
print(weights.tolist())
print(fruit.tolist())

print(weights.groupby(fruit).mean())

[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]
['carrot', 'banana', 'carrot', 'apple', 'banana', 'banana', 'apple', 'apple', 'banana', 'apple']
apple     7.25
banana    5.50
carrot    2.00
dtype: float64


In [154]:
# 26
p = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
q = pd.Series([10, 9, 8, 7, 6, 5, 4, 3, 2, 1])
dist = np.linalg.norm(p - q)
print(dist)

18.16590212458495


In [155]:
# 27
from scipy.signal import find_peaks
ser = pd.Series([2, 10, 3, 4, 9, 10, 2, 7, 3])
peak_idx, _ = find_peaks(ser)
print(peak_idx)

[1 5 7]


In [156]:
# 28
from collections import Counter
my_str = 'dbc deb abed gade'
symbol = Counter(my_str).most_common(1)[0][0]

print(my_str.replace(' ', symbol))

dbcddebdabeddgade


In [157]:
# 29
ser = pd.Series(np.random.randint(1,10,10), pd.date_range('2000-01-01', periods=10))
ser

2000-01-01    7
2000-01-02    4
2000-01-03    1
2000-01-04    3
2000-01-05    7
2000-01-06    7
2000-01-07    4
2000-01-08    1
2000-01-09    8
2000-01-10    3
Freq: D, dtype: int32

In [158]:
# 30
ser = pd.Series([1,10,3,np.nan], index=pd.to_datetime(['2000-01-01', '2000-01-03', '2000-01-06', '2000-01-08']))
print(ser)

print(ser.resample('D').ffill())

2000-01-01     1.0
2000-01-03    10.0
2000-01-06     3.0
2000-01-08     NaN
dtype: float64
2000-01-01     1.0
2000-01-02     1.0
2000-01-03    10.0
2000-01-04    10.0
2000-01-05    10.0
2000-01-06     3.0
2000-01-07     3.0
2000-01-08     NaN
Freq: D, dtype: float64


In [159]:
# 31
ser = pd.Series(np.arange(20) + np.random.normal(1, 10, 20))
autocorr = [ser.autocorr(lag=i).round(2) for i in range(19)]
print(autocorr)
print(np.argmax(np.abs(autocorr[1:]))+1)

[1.0, 0.19, 0.01, -0.29, -0.18, -0.07, 0.07, -0.17, 0.32, 0.01, -0.01, 0.2, 0.27, 0.62, -0.16, -0.95, -0.12, 0.74, -1.0]
18


In [160]:
# 32
url = 'https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv'
df = pd.read_csv(url)

chunk = 50
print(df.loc[df.index % chunk == 0])

         crim    zn  indus  chas    nox  ...  tax  ptratio       b  lstat  \
0     0.00632  18.0   2.31     0  0.538  ...  296     15.3  396.90   4.98   
50    0.08873  21.0   5.64     0  0.439  ...  243     16.8  395.56  13.45   
100   0.14866   0.0   8.56     0  0.520  ...  384     20.9  394.76   9.42   
150   1.65660   0.0  19.58     0  0.871  ...  403     14.7  372.80  14.10   
200   0.01778  95.0   1.47     0  0.403  ...  402     17.0  384.30   4.45   
..        ...   ...    ...   ...    ...  ...  ...      ...     ...    ...   
300   0.04417  70.0   2.24     0  0.400  ...  358     14.8  390.86   6.07   
350   0.06211  40.0   1.25     0  0.429  ...  335     19.7  396.90   5.98   
400  25.04610   0.0  18.10     0  0.693  ...  666     20.2  396.90  26.77   
450   6.71772   0.0  18.10     0  0.713  ...  666     20.2    0.32  17.44   
500   0.22438   0.0   9.69     0  0.585  ...  391     19.2  396.90  14.33   

     medv  
0    24.0  
50   19.7  
100  27.5  
150  21.5  
200  32.9  
.. 

In [161]:
# 33
url = 'https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv'
df = pd.read_csv(url, converters={'medv': lambda medv: 'High' if float(medv) > 25 else 'Low'})
df.head()

crim    zn  indus  chas    nox  ...  tax  ptratio       b  lstat  medv
0  0.00632  18.0   2.31     0  0.538  ...  296     15.3  396.90   4.98   Low
1  0.02731   0.0   7.07     0  0.469  ...  242     17.8  396.90   9.14   Low
2  0.02729   0.0   7.07     0  0.469  ...  242     17.8  392.83   4.03  High
3  0.03237   0.0   2.18     0  0.458  ...  222     18.7  394.63   2.94  High
4  0.06905   0.0   2.18     0  0.458  ...  222     18.7  396.90   5.33  High

[5 rows x 14 columns]

In [162]:
# 34
L = pd.Series(range(15))

df = pd.DataFrame(columns=['1', '2', '3', '4'])
series_length = len(L)
for i in range(0, series_length - 3, 2):
    df.loc[i] = [L[i], L[i + 1], L[i + 2], L[i + 3]]

df

1   2   3   4
0    0   1   2   3
2    2   3   4   5
4    4   5   6   7
6    6   7   8   9
8    8   9  10  11
10  10  11  12  13

In [163]:
# 35
url = 'https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv'
df = pd.read_csv(url, usecols=['crim', 'medv'])
df.head()

crim  medv
0  0.00632  24.0
1  0.02731  21.6
2  0.02729  34.7
3  0.03237  33.4
4  0.06905  36.2

In [164]:
# 36
url = 'https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv'
df = pd.read_csv(url)

rows_range = df.index
columns = df.columns
types = df.dtypes
df_stats = df.describe()
df_np = df.values
df_list = df.values.tolist()

print(rows_range, columns, types, df_stats, df_np, df_list)

RangeIndex(start=0, stop=93, step=1) Index(['Manufacturer', 'Model', 'Type', 'Min.Price', 'Price', 'Max.Price',
       'MPG.city', 'MPG.highway', 'AirBags', 'DriveTrain', 'Cylinders',
       'EngineSize', 'Horsepower', 'RPM', 'Rev.per.mile', 'Man.trans.avail',
       'Fuel.tank.capacity', 'Passengers', 'Length', 'Wheelbase', 'Width',
       'Turn.circle', 'Rear.seat.room', 'Luggage.room', 'Weight', 'Origin',
       'Make'],
      dtype='object') Manufacturer       object
Model              object
Type               object
Min.Price         float64
Price             float64
                   ...   
Rear.seat.room    float64
Luggage.room      float64
Weight            float64
Origin             object
Make               object
Length: 27, dtype: object        Min.Price      Price  Max.Price   MPG.city  MPG.highway  ...  \
count  86.000000  91.000000  88.000000  84.000000    91.000000  ...   
mean   17.118605  19.616484  21.459091  22.404762    29.065934  ...   
std     8.828290   9.7242

In [165]:
# 37
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

max_price = df["Price"].max()
result = df.loc[df.Price == max_price, ["Manufacturer", "Model", "Type", "Price"]]

print(result)
print(df.columns.get_loc("Price"))

     Manufacturer Model     Type  Price
58  Mercedes-Benz  300E  Midsize   61.9
4


In [166]:
# 38
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
print(df.columns)

df.rename(columns={"Type": "CarType"}, inplace=True)
df.columns = df.columns.map(lambda x: x.replace('.', '_'))
df.head()

Index(['Manufacturer', 'Model', 'Type', 'Min.Price', 'Price', 'Max.Price',
       'MPG.city', 'MPG.highway', 'AirBags', 'DriveTrain', 'Cylinders',
       'EngineSize', 'Horsepower', 'RPM', 'Rev.per.mile', 'Man.trans.avail',
       'Fuel.tank.capacity', 'Passengers', 'Length', 'Wheelbase', 'Width',
       'Turn.circle', 'Rear.seat.room', 'Luggage.room', 'Weight', 'Origin',
       'Make'],
      dtype='object')


Manufacturer    Model  CarType  Min_Price  Price  ...  Rear_seat_room  \
0        Acura  Integra    Small       12.9   15.9  ...            26.5   
1          NaN   Legend  Midsize       29.2   33.9  ...            30.0   
2         Audi       90  Compact       25.9   29.1  ...            28.0   
3         Audi      100  Midsize        NaN   37.7  ...            31.0   
4          BMW     535i  Midsize        NaN   30.0  ...            27.0   

   Luggage_room  Weight   Origin           Make  
0           NaN  2705.0  non-USA  Acura Integra  
1          15.0  3560.0  non-USA   Acura Legend  
2          14.0  3375.0  non-USA        Audi 90  
3          17.0  3405.0  non-USA       Audi 100  
4          13.0  3640.0  non-USA       BMW 535i  

[5 rows x 27 columns]

In [167]:
# 39
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

print(df.isnull().values.any())

True


In [168]:
# 40
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
null_columns = df.apply(lambda x: x.isnull().sum())
print(null_columns, '\n\n', null_columns.idxmax())

Manufacturer       4
Model              1
Type               3
Min.Price          7
Price              2
                  ..
Rear.seat.room     4
Luggage.room      19
Weight             7
Origin             5
Make               3
Length: 27, dtype: int64 

 AirBags


In [169]:
# 41
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

min_price_avg = df["Min.Price"].mean()
max_price_avg = df["Max.Price"].mean()

df["Min.Price"] = df["Min.Price"].fillna(min_price_avg)
df["Max.Price"] = df["Max.Price"].fillna(max_price_avg)

df

Manufacturer    Model     Type  Min.Price  Price  ...  Rear.seat.room  \
0         Acura  Integra    Small  12.900000   15.9  ...            26.5   
1           NaN   Legend  Midsize  29.200000   33.9  ...            30.0   
2          Audi       90  Compact  25.900000   29.1  ...            28.0   
3          Audi      100  Midsize  17.118605   37.7  ...            31.0   
4           BMW     535i  Midsize  17.118605   30.0  ...            27.0   
..          ...      ...      ...        ...    ...  ...             ...   
88   Volkswagen  Eurovan      Van  16.600000   19.7  ...            34.0   
89   Volkswagen   Passat  Compact  17.600000   20.0  ...            31.5   
90   Volkswagen  Corrado   Sporty  22.900000   23.3  ...            26.0   
91        Volvo      240  Compact  21.800000   22.7  ...            29.5   
92          NaN      850  Midsize  24.800000   26.7  ...            30.0   

    Luggage.room  Weight   Origin                Make  
0            NaN  2705.0  non-USA       Acura Integra  
1           15.0  3560.0  non-USA        Acura Legend  
2           14.0  3375.0  non-USA             Audi 90  
3           17.0  3405.0  non-USA            Audi 100  
4           13.0  3640.0  non-USA            BMW 535i  
..           ...     ...      ...                 ...  
88           NaN  3960.0      NaN  Volkswagen Eurovan  
89          14.0  2985.0  non-USA   Volkswagen Passat  
90          15.0  2810.0  non-USA  Volkswagen Corrado  
91          14.0  2985.0  non-USA           Volvo 240  
92          15.0  3245.0  non-USA           Volvo 850  

[93 rows x 27 columns]

In [170]:
# 42
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

d = {"Min.Price": np.nanmean, "Max.Price": np.nanmedian}
df[["Min.Price", "Max.Price"]] = df[["Min.Price", "Max.Price"]].apply(lambda x, d: x.fillna(d[x.name](x)), args=(d, ))
df

Manufacturer    Model     Type  Min.Price  Price  ...  Rear.seat.room  \
0         Acura  Integra    Small  12.900000   15.9  ...            26.5   
1           NaN   Legend  Midsize  29.200000   33.9  ...            30.0   
2          Audi       90  Compact  25.900000   29.1  ...            28.0   
3          Audi      100  Midsize  17.118605   37.7  ...            31.0   
4           BMW     535i  Midsize  17.118605   30.0  ...            27.0   
..          ...      ...      ...        ...    ...  ...             ...   
88   Volkswagen  Eurovan      Van  16.600000   19.7  ...            34.0   
89   Volkswagen   Passat  Compact  17.600000   20.0  ...            31.5   
90   Volkswagen  Corrado   Sporty  22.900000   23.3  ...            26.0   
91        Volvo      240  Compact  21.800000   22.7  ...            29.5   
92          NaN      850  Midsize  24.800000   26.7  ...            30.0   

    Luggage.room  Weight   Origin                Make  
0            NaN  2705.0  non-USA       Acura Integra  
1           15.0  3560.0  non-USA        Acura Legend  
2           14.0  3375.0  non-USA             Audi 90  
3           17.0  3405.0  non-USA            Audi 100  
4           13.0  3640.0  non-USA            BMW 535i  
..           ...     ...      ...                 ...  
88           NaN  3960.0      NaN  Volkswagen Eurovan  
89          14.0  2985.0  non-USA   Volkswagen Passat  
90          15.0  2810.0  non-USA  Volkswagen Corrado  
91          14.0  2985.0  non-USA           Volvo 240  
92          15.0  3245.0  non-USA           Volvo 850  

[93 rows x 27 columns]

In [171]:
# 43
df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))
df[['a']]

a
0   0
1   5
2  10
3  15

In [172]:
# 44
df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))

In [173]:
def swap_cols(column_to_swap: str, swapper_column: str):
    cols = list(df.columns.values)
    index_to_swap = cols.index(column_to_swap)
    swapper_index = cols.index(swapper_column)
    temp = cols[swapper_index]
    cols[swapper_index] = cols[index_to_swap]
    cols[index_to_swap] = temp
    return df[cols]

In [174]:
print(swap_cols('a', 'c'))
print(df[list(df.columns.values)[::-1]])

    c   b   a   d   e
0   2   1   0   3   4
1   7   6   5   8   9
2  12  11  10  13  14
3  17  16  15  18  19
    e   d   c   b   a
0   4   3   2   1   0
1   9   8   7   6   5
2  14  13  12  11  10
3  19  18  17  16  15


In [175]:
# 45
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

pd.set_option('display.max_columns', 10)
pd.set_option('display.max_rows', 10)
df

Manufacturer    Model     Type  Min.Price  Price  ...  Rear.seat.room  \
0         Acura  Integra    Small       12.9   15.9  ...            26.5   
1           NaN   Legend  Midsize       29.2   33.9  ...            30.0   
2          Audi       90  Compact       25.9   29.1  ...            28.0   
3          Audi      100  Midsize        NaN   37.7  ...            31.0   
4           BMW     535i  Midsize        NaN   30.0  ...            27.0   
..          ...      ...      ...        ...    ...  ...             ...   
88   Volkswagen  Eurovan      Van       16.6   19.7  ...            34.0   
89   Volkswagen   Passat  Compact       17.6   20.0  ...            31.5   
90   Volkswagen  Corrado   Sporty       22.9   23.3  ...            26.0   
91        Volvo      240  Compact       21.8   22.7  ...            29.5   
92          NaN      850  Midsize       24.8   26.7  ...            30.0   

    Luggage.room  Weight   Origin                Make  
0            NaN  2705.0  non-USA       Acura Integra  
1           15.0  3560.0  non-USA        Acura Legend  
2           14.0  3375.0  non-USA             Audi 90  
3           17.0  3405.0  non-USA            Audi 100  
4           13.0  3640.0  non-USA            BMW 535i  
..           ...     ...      ...                 ...  
88           NaN  3960.0      NaN  Volkswagen Eurovan  
89          14.0  2985.0  non-USA   Volkswagen Passat  
90          15.0  2810.0  non-USA  Volkswagen Corrado  
91          14.0  2985.0  non-USA           Volvo 240  
92          15.0  3245.0  non-USA           Volvo 850  

[93 rows x 27 columns]

In [176]:
# 46
df = pd.DataFrame(np.random.random(4)**10, columns=['random'])
pd.options.display.float_format = '{:,.4f}'.format
df

random
0  0.0000
1  0.0931
2  0.0040
3  0.0000

In [177]:
# 47
df = pd.DataFrame(np.random.random(4), columns=['random'])
print(df)
pd.options.display.float_format = '{0:.2%}'.format
print(df)
pd.options.display.float_format = None
print(df)

   random
0  0.4472
1  0.1499
2  0.7296
3  0.5981
   random
0  44.72%
1  14.99%
2  72.96%
3  59.81%
     random
0  0.447242
1  0.149931
2  0.729643
3  0.598137


In [178]:
# 48
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
print(df.loc[::20][['Manufacturer', 'Model', 'Type']])

   Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small


In [179]:
# 49
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv', usecols=[0,1,2,3,5])

df[['Manufacturer', 'Model', 'Type']] = df[['Manufacturer', 'Model', 'Type']].fillna('missing')
df.index = df.Manufacturer + '_' + df.Model + '_' + df.Type
print(df.head())

                       Manufacturer    Model     Type  Min.Price  Max.Price
Acura_Integra_Small           Acura  Integra    Small       12.9       18.8
missing_Legend_Midsize      missing   Legend  Midsize       29.2       38.7
Audi_90_Compact                Audi       90  Compact       25.9       32.3
Audi_100_Midsize               Audi      100  Midsize        NaN       44.6
BMW_535i_Midsize                BMW     535i  Midsize        NaN        NaN


In [180]:
# 50
df = pd.DataFrame(np.random.randint(1, 30, 30).reshape(10,-1), columns=list('abc'))
df

a   b   c
0  20  12  19
1  17   6  16
2  16   6  20
3   2  12   6
4  28  15   7
5  13  23   5
6   4  19  15
7  25  16   8
8  17   6  12
9  29   9   4

In [181]:
df = df.sort_values(by=['a'], ascending=False)
df.iloc[4]

a    17
b     6
c    16
Name: 1, dtype: int32

In [182]:
# 51
ser = pd.Series(np.random.randint(1, 100, 15))
print(ser)
avg = ser.mean()

np.argwhere(ser > avg)[1]

0     68
1     94
2     39
3     30
4     95
      ..
10    24
11    15
12    84
13    76
14    29
Length: 15, dtype: int32


array([1], dtype=int64)

In [183]:
# 52
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
print(df)

df1 = df.sum(axis=1, numeric_only=True)
print(df1)

df2 = df1[df1 > 100]
print(df2)

df3 = df2[-2::]
print(df3)

     0   1   2   3
0   28  10  21  33
1   34  33  12  25
2   20  33  23  38
3   19  17  36  19
4   26  14  13  25
..  ..  ..  ..  ..
10  22  34  10  34
11  33  15  12  28
12  28  19  35  26
13  21  14  24  39
14  17  15  19  25

[15 rows x 4 columns]
0      92
1     104
2     114
3      91
4      78
     ... 
10    100
11     88
12    108
13     98
14     76
Length: 15, dtype: int64
1     104
2     114
5     125
6     106
8     111
9     103
12    108
dtype: int64
9     103
12    108
dtype: int64


In [184]:
# 53
ser = pd.Series(np.logspace(-2, 2, 30))
print(ser)

val_5 = ser.quantile(0.05)
val_95 = ser.quantile(0.95)

ser[ser < val_5] = val_5
ser[ser > val_95] = val_95

print(ser)

0       0.010000
1       0.013738
2       0.018874
3       0.025929
4       0.035622
         ...    
25     28.072162
26     38.566204
27     52.983169
28     72.789538
29    100.000000
Length: 30, dtype: float64
0      0.016049
1      0.016049
2      0.018874
3      0.025929
4      0.035622
        ...    
25    28.072162
26    38.566204
27    52.983169
28    63.876672
29    63.876672
Length: 30, dtype: float64


In [185]:
# 54
df = pd.DataFrame(np.random.randint(-20, 50, 100).reshape(10,-1))

arr = df[df > 0].values.flatten()
arr_qualified = arr[~np.isnan(arr)]

n = int(arr_qualified.shape[0]**.5)

top_indexes = np.argsort(arr_qualified)[::-1]
output = np.take(arr_qualified, sorted(top_indexes[:n**2])).reshape(n, -1)
print(output)

[[28.  4. 13. 10. 41. 43.  4. 26.]
 [ 6. 49. 16. 19.  9. 28. 27. 27.]
 [25. 39. 49. 10. 46. 47. 49.  5.]
 [11.  6.  9. 16.  8. 30. 22. 30.]
 [11. 28. 25. 40. 22.  9. 42. 12.]
 [30. 36. 48. 27. 15. 17. 23. 23.]
 [20. 40. 49. 30. 22. 23. 35. 28.]
 [ 8. 13. 17. 18. 37. 33. 39. 34.]]


In [186]:
# 55
df = pd.DataFrame(np.arange(25).reshape(5, -1))
print(df)

temp = df.iloc[1].copy()
df.iloc[1] = df.iloc[2].copy()
df.iloc[2] = temp
print('\n', df)

    0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24

     0   1   2   3   4
0   0   1   2   3   4
1  10  11  12  13  14
2   5   6   7   8   9
3  15  16  17  18  19
4  20  21  22  23  24


In [187]:
# 56
df = pd.DataFrame(np.arange(25).reshape(5, -1))
print(df)
df = df.iloc[::-1]
print("\n", df)

    0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24

     0   1   2   3   4
4  20  21  22  23  24
3  15  16  17  18  19
2  10  11  12  13  14
1   5   6   7   8   9
0   0   1   2   3   4


In [188]:
# 57
df = pd.DataFrame(np.arange(25).reshape(5,-1), columns=list('abcde'))
df

a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24

In [189]:
df = pd.concat([pd.get_dummies(df['a'], dtype='int'), df[list('bcde')]], axis=1)
df

0  5  10  15  20   b   c   d   e
0  1  0   0   0   0   1   2   3   4
1  0  1   0   0   0   6   7   8   9
2  0  0   1   0   0  11  12  13  14
3  0  0   0   1   0  16  17  18  19
4  0  0   0   0   1  21  22  23  24

In [190]:
# 58
df = pd.DataFrame(np.random.randint(1,100, 40).reshape(10, -1))
print(df)

columns_max_values = df.sum()
print("\n", columns_max_values)

max_column = columns_max_values.idxmax()
print("\n", max_column)

    0   1   2   3
0  48   4  59  38
1  44  16  13  73
2   4  21  74  52
3  26  85  27  16
4  79  18  18   5
5  97  26  79   5
6  82  91   2  48
7  55  27  35  25
8  94  11  46  83
9  50   7  21  22

 0    579
1    306
2    374
3    367
dtype: int64

 0


In [191]:
# 59
df = pd.DataFrame(np.random.randint(1,100, 40).reshape(10, -1), columns=list('pqrs'), index=list('abcdefghij'))
df

p   q   r   s
a  70  49  60  34
b   4  30  71   6
c  88  87  69  76
d  78  44  99  97
e  17  40  64  38
f  28   2  10  67
g  15  73  11  47
h  29  22   8  82
i  28  66  25   6
j  30  29  85  35

In [192]:
new_rows = []
distances = []

for i, row in df.iterrows():
    curr = row
    rest = df.drop(i) 
    
    e_dists = {}  
    
    for j, contestant in rest.iterrows():        
        e_dists.update({j: round(np.linalg.norm(curr.values - contestant.values))})        
    
    new_rows.append(max(e_dists, key=e_dists.get))
    distances.append(max(e_dists.values()))

df['nearest_row'] = new_rows
df['dist'] = distances
df

p   q   r   s nearest_row  dist
a  70  49  60  34           f    87
b   4  30  71   6           c   123
c  88  87  69  76           b   123
d  78  44  99  97           i   129
e  17  40  64  38           c    93
f  28   2  10  67           c   120
g  15  73  11  47           d   123
h  29  22   8  82           c   107
i  28  66  25   6           d   129
j  30  29  85  35           c    93

In [193]:
# 60
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1), columns=list('pqrstuvwxy'), index=list('abcdefgh'))
print(df, "\n")

abs_corr = np.abs(df.corr())
print(abs_corr, "\n")

max_corr = abs_corr.apply(lambda x: sorted(x)[-2])
print(np.round(max_corr.tolist(), 2))


    p   q   r   s   t   u   v   w   x   y
a  87  83  35   8  24  10  26  54  30  79
b  23  39  45  72  51  70  97  12  91  52
c  23  57  18  46  17  74  42  73  73  82
d  65  99  93  81  21  90  14  63  10  38
e  99  11  80  80  69  75   7  89  30  93
f  22  64  74  18  94  22  81  90  49  71
g  17  35  38  88  94  16  62  17  69  21
h  78  74  50  43  14   1   6  31  63  47 

          p         q         r         s         t         u         v  \
p  1.000000  0.120741  0.364605  0.099746  0.403472  0.027728  0.840446   
q  0.120741  1.000000  0.104084  0.456209  0.595435  0.157023  0.251404   
r  0.364605  0.104084  1.000000  0.276092  0.222253  0.329320  0.253806   
s  0.099746  0.456209  0.276092  1.000000  0.207682  0.545810  0.036029   
t  0.403472  0.595435  0.222253  0.207682  1.000000  0.172294  0.542937   
u  0.027728  0.157023  0.329320  0.545810  0.172294  1.000000  0.030792   
v  0.840446  0.251404  0.253806  0.036029  0.542937  0.030792  1.000000   
w  0.279471  0.03276

In [194]:
# 61
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))
print(df, '\n')

print(np.min(df, axis=1)/np.max(df, axis=1))

    0   1   2   3   4   5   6   7   8   9
0  91  42  49  34  27  98  74  61  84  55
1  34  60  60  90  18  36  15  60  62  77
2  81  48  41  44  45  24  29  10  44   8
3  18  90  30  21  94  47  18  20  31  65
4  46  21  79  56  24  90  73  34  24  96
5  27  60   8  14   3  11  25  85  42  89
6  77  32  30  66  48  54  86  20  55  31
7  61  63  69  44  50  30  51  92  83  18 

0    0.275510
1    0.166667
2    0.098765
3    0.191489
4    0.218750
5    0.033708
6    0.232558
7    0.195652
dtype: float64


In [195]:
# 62
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))
print(df, '\n')

updated_df = df.apply(lambda x: sorted(list(set(x.to_list())))[-2], axis=1)
df['penultimate'] = updated_df
print(df)

    0   1   2   3   4   5   6   7   8   9
0   2  39  45   7  23  81  62  90  34  91
1  12  83   7  95  31  51  88  16  78  45
2  46  37  67  42   8  36  81  86  32  73
3  16  18  32  82  79  22  90  16  64  64
4  81  22  90  69  18  73  45  13  62  24
5  89  34   7  54  72  82  30  14  10  20
6  78  99  33  43   2  95  39  44  18  87
7  80  69  37   9  91  90  95  37  31  82 

    0   1   2   3   4  ...   6   7   8   9  penultimate
0   2  39  45   7  23  ...  62  90  34  91           90
1  12  83   7  95  31  ...  88  16  78  45           88
2  46  37  67  42   8  ...  81  86  32  73           81
3  16  18  32  82  79  ...  90  16  64  64           82
4  81  22  90  69  18  ...  45  13  62  24           81
5  89  34   7  54  72  ...  30  14  10  20           82
6  78  99  33  43   2  ...  39  44  18  87           95
7  80  69  37   9  91  ...  95  37  31  82           91

[8 rows x 11 columns]


In [196]:
# 63
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))
print(df, '\n')

df1 = df.apply(lambda row: (row - row.mean()) / row.std(), axis=1)
print(df1, '\n')

df2 = df.apply(lambda x: ((x.max() - x)/(x.max() - x.min())).round(2))
print(df2, '\n')

    0   1   2   3   4   5   6   7   8   9
0  14  10  19   2  49  59   7  28  38  64
1  29  73  28  34  76  65  99  83  44  66
2  44  44  82  66  64  68  78  84  32  12
3  79  98  79  32  95  27  76  65   6   8
4  25   4  47  32  14  39  65  38   7  53
5  79  31  23  64  51  36  85  92  59  13
6  53  74  24  83  76  90  54  16  87  28
7  49  85  55  52  74  10  94  37  91  76 

          0         1         2         3         4         5         6  \
0 -0.670374 -0.849140 -0.446916 -1.206673  0.893832  1.340747 -0.983215   
1 -1.247320  0.540370 -1.287949 -1.044173  0.662258  0.215335  1.596732   
2 -0.566681 -0.566681  1.040324  0.363691  0.279111  0.448270  0.871166   
3  0.642348  1.184774  0.642348 -0.699445  1.099128 -0.842189  0.556701   
4 -0.368956 -1.415994  0.727940 -0.019944 -0.917404  0.329069  1.625401   
5  0.945170 -0.820128 -1.114344  0.393514 -0.084587 -0.636243  1.165832   
6 -0.198228  0.558642 -1.243428  0.883014  0.630724  1.135304 -0.162186   
7 -0.499527  0.85257

In [197]:
# 64
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))
print(df, '\n')

rows = df.shape[0]
corr = [df.iloc[i].corr(df.iloc[i + 1]) for i in range(rows - 1)]
print(corr)

    0   1   2   3   4   5   6   7   8   9
0  27  30   1  58  31  23  79  16  25  24
1  67  43  45  28  28  63  78  84  38  66
2  36  71  65  95  94  62  72  12  30  41
3  16   3   2  38  61  53  28  47  63  45
4  54  57  95  93  53  82  77   9  72  81
5  69  72  48   9  17  77  13  51  13  12
6  39  45  38  81  23  31  79  55  63  63
7  14  41  90  43  29  12  97  79  49  73 

[0.04237408349621425, -0.6320048903302954, -0.12836287291402979, -0.1669569115220716, -0.2842419413718246, -0.6055377854757997, 0.5111860053789079]


In [198]:
# 65
df = pd.DataFrame(np.random.randint(1,100, 100).reshape(10, -1))
print(df, '\n')

for i in range(df.shape[0]):
    df.iat[i, i] = 0
    df.iat[i, df.shape[0] - i - 1] = 0

print(df)

    0   1   2   3   4   5   6   7   8   9
0  35  74  76  17  90  29  48  31  37  51
1  79  74  35  19  72  10  63  58  62  31
2  14  81  92  96  28  18  62  58  38  25
3  51  16  39  19  59  61  80  67  82  73
4  55  38  30  44  75  47  98  15  71   5
5   8  25  45  20  92  63  81  75  13  39
6  57  38  53   4  39  44  89  90  53  36
7   7  89  71   3  78  23  71  29  20  47
8  21  54  99  87  20  68  35  86  32  42
9  45  92  18  56  60  58  11  58  80  22 

    0   1   2   3   4   5   6   7   8   9
0   0  74  76  17  90  29  48  31  37   0
1  79   0  35  19  72  10  63  58   0  31
2  14  81   0  96  28  18  62   0  38  25
3  51  16  39   0  59  61   0  67  82  73
4  55  38  30  44   0   0  98  15  71   5
5   8  25  45  20   0   0  81  75  13  39
6  57  38  53   0  39  44   0  90  53  36
7   7  89   0   3  78  23  71   0  20  47
8  21   0  99  87  20  68  35  86   0  42
9   0  92  18  56  60  58  11  58  80   0


In [199]:
# 66
df = pd.DataFrame({'col1': ['apple', 'banana', 'orange'] * 3,
                   'col2': np.random.rand(9),
                   'col3': np.random.randint(0, 15, 9)})

df_grouped = df.groupby(['col1'])

print(df, '\n', df_grouped.get_group('apple'))

     col1      col2  col3
0   apple  0.368871     6
1  banana  0.360286     5
2  orange  0.843326     9
3   apple  0.598898    12
4  banana  0.163031    11
5  orange  0.730655     8
6   apple  0.859490     4
7  banana  0.617832     1
8  orange  0.629332    11 
     col1      col2  col3
0  apple  0.368871     6
3  apple  0.598898    12
6  apple  0.859490     4


In [200]:
# 67
df = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                   'rating': np.random.rand(9),
                   'price': np.random.randint(0, 15, 9)})

df_grouped = df.groupby(['fruit'])
print(df, '\n')

banana_group = df_grouped.get_group('banana')
print(banana_group, '\n')
print(banana_group.sort_values(by='rating').iloc[-2])


    fruit    rating  price
0   apple  0.037646     10
1  banana  0.879380     13
2  orange  0.420645      1
3   apple  0.181103     13
4  banana  0.200079      6
5  orange  0.968080      7
6   apple  0.950943      8
7  banana  0.230438      6
8  orange  0.680100      4 

    fruit    rating  price
1  banana  0.879380     13
4  banana  0.200079      6
7  banana  0.230438      6 

fruit       banana
rating    0.230438
price            6
Name: 7, dtype: object


In [201]:
# 68
df = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                   'rating': np.random.rand(9),
                   'price': np.random.randint(0, 15, 9)})
print(df, '\n')
grouped_items = df.groupby('fruit', as_index=False)['price'].mean()
print(grouped_items)


    fruit    rating  price
0   apple  0.831491     14
1  banana  0.992110      3
2  orange  0.778732      9
3   apple  0.537000     11
4  banana  0.928575      9
5  orange  0.136823      2
6   apple  0.427096      8
7  banana  0.613597     13
8  orange  0.265910      2 

    fruit      price
0   apple  11.000000
1  banana   8.333333
2  orange   4.333333


In [202]:
# 69
df1 = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                    'weight': ['high', 'medium', 'low'] * 3,
                    'price': np.random.randint(0, 15, 9)})

df2 = pd.DataFrame({'pazham': ['apple', 'orange', 'pine'] * 2,
                    'kilo': ['high', 'low'] * 3,
                    'price': np.random.randint(0, 15, 6)})

print(df1, '\n'*2, df2, '\n'*2)

merged = pd.merge(df1, df2,  how='inner', left_on=['fruit','weight'], right_on = ['pazham','kilo'])
print(merged)

    fruit  weight  price
0   apple    high     12
1  banana  medium      2
2  orange     low     14
3   apple    high      0
4  banana  medium      4
5  orange     low      6
6   apple    high      9
7  banana  medium      6
8  orange     low      5 

    pazham  kilo  price
0   apple  high      4
1  orange   low     11
2    pine  high      1
3   apple   low      6
4  orange  high      8
5    pine   low      0 


    fruit weight  price_x  pazham  kilo  price_y
0   apple   high       12   apple  high        4
1   apple   high        0   apple  high        4
2   apple   high        9   apple  high        4
3  orange    low       14  orange   low       11
4  orange    low        6  orange   low       11
5  orange    low        5  orange   low       11


In [203]:
# 70
df = pd.DataFrame(np.random.randint(1, 100, 20).reshape(-1, 4), columns = list('abcd'))
print(df, '\n')

df['lag1'] = df['a'].shift(1)
df['lead1'] = df['b'].shift(-1)

print(df)

    a   b   c   d
0  39  68  76  78
1  32  25  46  85
2  34  80  52  24
3   1  82  31  61
4  50  83  42   8 

    a   b   c   d  lag1  lead1
0  39  68  76  78   NaN   25.0
1  32  25  46  85  39.0   80.0
2  34  80  52  24  32.0   82.0
3   1  82  31  61  34.0   83.0
4  50  83  42   8   1.0    NaN


In [204]:
# 71
df = pd.DataFrame(np.random.randint(1, 10, 20).reshape(-1, 4), columns = list('abcd'))
print(df, '\n')

values, counts = np.unique(df.values,return_counts=True)
print(values, counts)

   a  b  c  d
0  5  6  1  4
1  9  2  8  6
2  8  9  3  9
3  4  6  1  3
4  3  2  4  8 

[1 2 3 4 5 6 8 9] [2 2 3 3 1 3 3 3]


In [205]:
# 72
df = pd.DataFrame(["STD, City    State",
"33, Kolkata    West Bengal",
"44, Chennai    Tamil Nadu",
"40, Hyderabad    Telengana",
"80, Bangalore    Karnataka"], columns=['row'])
print(df, '\n')

df = df.row.str.split(',|\t', expand=True)
head = df.iloc[0]
df = df[1:]
df.columns = head
print(df)


                          row
0          STD, City    State
1  33, Kolkata    West Bengal
2   44, Chennai    Tamil Nadu
3  40, Hyderabad    Telengana
4  80, Bangalore    Karnataka 

0 STD            City    State
1  33   Kolkata    West Bengal
2  44    Chennai    Tamil Nadu
3  40   Hyderabad    Telengana
4  80   Bangalore    Karnataka
